/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include "app.h"

#include <core.hpp>

std::string snow_owl::Greeter::greeting() {
	return std::string("Hello, World " + swl::cx::Core::version);
}

int main () {

#if defined(SWL_DEBUG)

	std::cout << "SnowOwl: Debug build" << std::endl;

#endif

	snow_owl::Greeter greeter;
	std::cout << greeter.greeting() << std::endl;

	return 0;
}
